import { CATEGORY_ICONS, type CategoryLucideIcon } from '@pesly/shared';
import {
  Apple,
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Calculator,
  Camera,
  Car,
  CircleQuestionMark,
  Clapperboard,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Ellipsis,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Heart,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  Palette,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Sandwich,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Ticket,
  TrainFront,
  TrendingUp,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** The shared icon keys mapped to Lucide components: nothing else reaches the page. */
export const CATEGORY_ICON_COMPONENTS: Record<CategoryLucideIcon, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  home: House,
  'heart-pulse': HeartPulse,
  clapperboard: Clapperboard,
  'shopping-bag': ShoppingBag,
  'graduation-cap': GraduationCap,
  receipt: Receipt,
  ellipsis: Ellipsis,
  banknote: Banknote,
  laptop: Laptop,
  'trending-up': TrendingUp,
  gift: Gift,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  plane: Plane,
  shirt: Shirt,
  'book-open': BookOpen,
  briefcase: Briefcase,
  coffee: Coffee,
  dumbbell: Dumbbell,
  'paw-print': PawPrint,
  baby: Baby,
  wrench: Wrench,
  pizza: Pizza,
  beer: Beer,
  wine: Wine,
  sandwich: Sandwich,
  apple: Apple,
  'shopping-cart': ShoppingCart,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  'train-front': TrainFront,
  smartphone: Smartphone,
  wifi: Wifi,
  zap: Zap,
  droplets: Droplets,
  flame: Flame,
  tv: Tv,
  music: Music,
  'gamepad-2': Gamepad2,
  camera: Camera,
  palette: Palette,
  pill: Pill,
  stethoscope: Stethoscope,
  scissors: Scissors,
  sparkles: Sparkles,
  umbrella: Umbrella,
  ticket: Ticket,
  landmark: Landmark,
  'credit-card': CreditCard,
  'hand-coins': HandCoins,
  calculator: Calculator,
  hammer: Hammer,
  sofa: Sofa,
  shield: Shield,
  heart: Heart,
  star: Star,
  globe: Globe,
};

export const FALLBACK_CATEGORY_ICON: LucideIcon = CircleQuestionMark;

export function isCategoryIcon(key: string): key is CategoryLucideIcon {
  return (CATEGORY_ICONS as readonly string[]).includes(key);
}
